/* tFormer v0.5.2*/
(function(x,m,p){var z=["button","submit"],A="text password select-one checkbox textarea range number email hidden file date datetime-local search tel time url month week".split(" "),B=["checkbox","select-one","select","file"],C="number date datetime-local time month week range".split(" "),D="timeout requestTimeout request validClass errorClass disabledClass processingClass rules validateEvent before onerror onvalid own eventBefore eventError eventValid".split(" "),q={errorClass:"error",processingClass:"processing",
disabledClass:"disabled",validClass:"valid",eventBefore:"tFormer:before",eventError:"tFormer:error",eventValid:"tFormer:valid",timeout:0,requestTimeout:2E3,validateEvent:"input keyup",fields:{},buttons:{},submitButtonControl:!0,submitButton:null},r=function(a,b){if(!(this instanceof r))return new r(a,b);var c=a,c="string"===typeof c?m.forms[c]:c,c=this.form="[object HTMLFormElement]"==toString.call(c)?c:null;if(null===this.form)return null;if(!c?0:c.getAttribute("empowered")){a:{for(var d=0,e=this.cache.length;d<
e;d++)if(this.cache[d].form==c){c=this.cache[d];break a}c=null}if(c)return c.set(b),c}else s(c,"empowered",1),s(c,"novalidate","novalidate");this.config=this.config||k(q);this.set(b);this.init();this.cache.push(this);return this},f=r.prototype;f.cache=[];f.init=function(){if(this.inited)return this;this.fields={};this.buttons={};this.inited=!0;this.invalid=this.holded=this.locked=0;this.valid=!0;this.fields={};this.buttons={};this.xhr={};this.xhrTimeout={};var a=this.get("submitButton");a&&(this.buttons.submit=
new t(this,a));for(var a=0,b=this.form.length;a<b;a++){var c=this.form[a],d=c.type,e="button"!==d?!c?null:c.getAttribute("name"):u(c,"check");-1!==l(A,d)&&e&&(this.fields[e]=new y(this,c));-1!==l(z,d)&&(e="submit"==d?d:e)&&!("submit"==e&&this.button[e])&&(this.buttons[e]=new t(this,c))}var g=this;this.form.onsubmit=function(a){a=a||x.event;var b=g.button("submit"),c=g.get("submitButtonControl"),d="function"==typeof g.get("submit"),e=b.get("processingClass"),f=g.valid&&d,v=function(a){a.preventDefault?
a.preventDefault():a.returnValue=!1};if(e&&b.hasClass(e)||g.locked)return v(a),!1;f&&v(a);g.valid&&(c&&b.processing(!0),d&&g.execute(g.form,"submit",[a,g]));if(f)return!1;try{if(!g.valid&&!g.validate({no_timeout:!0}))return v(a),b.processing(!1),!1;if(d)return v(a),g.execute(g.form,"submit",[a,g]),!1;g.form.submit();return!0}catch(h){}};this.validate({highlight:!1,fire_event:!1,silence:!0});return this.submitControl()};f.destroy=function(){for(var a in this.fields)this.fields[a].destroy();for(a in this.buttons)this.buttons[a].destroy();
this.inited=!1;return this};f.drop=function(){var a=this.fields,b=this.buttons;this.destroy();this.set(k(q));for(var c in a)a[c].drop();for(c in b)b[c].drop();this.locked=0;return this.init()};f.validate=function(a){var b=this.fields,c=0,d;for(d in b)c+=b[d].validate(a||{})?0:1;this.invalid=c;this.valid=0===c;return 0===c};f.toObject=function(){for(var a=this.form,b={},c=0,d=a.length;c<d;c++){var e=a[c],g=!e?null:e.getAttribute("name");"checkbox"==e.type?b[g]=e.checked:"radio"==e.type?(b[g]||(b[g]=
""),e.checked&&(b[g]=e.value)):b[g]=e.value}return b};f.get=function(a){return this.config[a]};f.set=function(a){var b=this.inited;b&&this.destroy();this.config=w(this.config,a);b&&this.init();return this};f.field=function(a){return this.fields[a]};f.button=function(a){return this.buttons[a]};f.submit=function(a){if(!this.config)return this;"function"==typeof a&&(this.config.submit=a);return this};f.submitControl=function(a){var b=this.button("submit"),c=this.get("submitButtonControl");this.valid=
0===this.invalid&&0===this.holded&&0===this.locked;a=!1===a||!0===a?a:this.valid;if(b&&c)b[a?"enable":"disable"]();return this};f.submitDisable=function(){return this.submitControl(!1)};f.submitEnable=function(){return this.submitControl(!0)};f.processing=function(a){var b=this.button("submit");b&&b.processing(a);return this};f.lock=function(a){this.locked+=a||1;return this.submitControl(!1)};f.unlock=function(a){this.locked-=a||1;return this.submitControl()};f.execute=function(a,b,c){"string"==typeof b&&
(b=this.get(b));return"function"==typeof b?b.apply(a,c||[]):null};x.tFormer=r;var f=function(){},h=f.prototype;h.destroy=function(){for(var a=this.el,b=this.events,c=0,d=b.length;c<d;c++)this.off(b[0][0],b[0][1]);this.removeClass(this.get("errorClass"));this.removeClass(this.get("desabledClass"));this.removeClass(this.get("processignClass"));u(a,"holded",null);u(a,"error",null);this.timer&&clearTimeout(this.timer);this.xhr&&this.xhr.abort();this.xhrTimeout&&clearTimeout(this.xhrTimeout);this.valid||
(this.parent.invalid=0!==this.parent.invalid?this.parent.invalid-1:0);this.parent.submitControl();this.inited=!1;return this};h.drop=function(){return this.set(k(q))};h.set=function(a){var b=!this.el?null:this.el.getAttribute("name"),c=this.inited;c&&this.destroy();for(var d in a)if(~l(D,d)){var e=d,g=a[d];this.config[e]=g;this.parent.config.fields[b]||(this.parent.config.fields[b]=k(q));this.parent.config.fields[b][e]=g}c&&this.init();return this};h.get=function(a){return this.config[a]};h.on=function(a,
b,c){c=c||this.el;a=a.split(" ");for(var d=0,e=a.length;d<e;d++)c.addEventListener?c.addEventListener(a[d],b,!1):element.attachEvent?c.attachEvent("on"+a[d],b):c[a[d]]=b,this.events.push([a[d],b]);return this};h.off=function(a,b){var c=this.el,d=this.events;a=a.split(" ");if(!b){for(var c=0,e=d.length;c<e;c++)-1!==l(a,d[c][0])&&d.splice(c,1);return this}c.removeEventListener?c.removeEventListener(a,b,!1):c.detachEvent?c.detachEvent("on"+a,b):c[a]=null;c=0;for(e=d.length;c<e;c++)if(-1!==l(a,d[c][0])&&
d[c][1]==b){d.splice(c,1);break}return this};h.trigger=function(a){var b=this.el,c;if(!this.silence){if(m.createEventObject)return c=m.createEventObject(),b.fireEvent("on"+a,c);c=m.createEvent("HTMLEvents");c.initEvent(a,!0,!0);return!b.dispatchEvent(c)}};h.addClass=function(a){var b=this.el,c=b.className.split(" ")||[];if(-1===l(c,a)){c.push(a);a=c;if("[object Array]"==Object.prototype.toString.call(a))for(var c=[],d=0,e=a.length;d<e;d++)""!==a[d]&&c.push(a[d]);else c=void 0;b.className=0<c.length?
c.join(" "):""}return this};h.removeClass=function(a){var b=this.el;this.hasClass(a)&&(b.className=b.className.replace(RegExp("(\\s|^)"+a+"(\\s|$)")," "));return this};h.hasClass=function(a){return!!~(" "+this.el.className+" ").indexOf(" "+a+" ")};h.data=function(a,b){var c=u(this.el,a,b);return b===p?c:this};h.attr=function(a,b){var c=this.el;switch(b){case null:c&&c.removeAttribute(a);break;case p:return!c?null:c.getAttribute(a);default:s(c,a,b)}};h.processing=function(a){var b=this.get("processingClass"),
c=this.hasClass(b);!1===a||null===a&&c?this.removeClass(b):(!0===a||null===a&&c)&&this.addClass(b);return this};var h=function(a,b){var c=function(){};c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.superclass=b.prototype},y=function(a,b){var c=b.type,d,e,g,f,h=[];this.parent=a;this.el=b;this.config={};this.events=[];d=this.attr("name");e=null!==this.attr("required");g=this.attr("min");f=this.attr("max");d=a.config.fields?a.config.fields[d]:{};"string"==typeof d&&(d={rules:d});
this.set(w(k(a.config),k(d)));this.config.rules=this.config.rules||this.data("rules");e&&h.push("*");"email"==c&&h.push("@");"url"==c&&h.push("url");"number"==c&&(h.push("num"),null!==g&&h.push(">"+g),null!==f&&h.push("<"+f));0<h.length&&(this.config.rules=_v_("").rules(this.config.rules||this.data("rules")).addRule(h.join(" ")).rule);this.value=b.value;this.validationStart="v_start";this.validationSuccess="v_success";this.validationError="v_error";this.fire_event=this.highlight=!0;this.silence=!1;
return this.init()};h(y,f);var j=y.prototype;j.init=function(){var a=this,b=a.el.value,c=a.attr("type"),d="checkbox"==c;if(a.inited)return a;a.events=[];a.valid=!0;a.holded=!1;a.value=b;b=a.get("validateEvent");~l(C,c)&&-1===b.indexOf("change")&&(b=b.split(" "),b.push("change"),b=b.join(" "));~l(B,c)&&(b="change");a.set({validateEvent:b});a.on(b,function(){if(a.get("rules")&&(a.value!=a.el.value||d)){a.value=a.el.value;a.removeClass(a.get("errorClass"));a.removeClass(a.get("processingClass"));a.parent.invalid+=
a.valid?1:0;a.valid=!1;a.removeClass(a.get("errorClass"));a.parent.submitControl();var b=a.get("timeout");0<a.get("timeout")?(a.timer&&clearTimeout(a.timer),a.timer=setTimeout(function(){a.validate()},b)):a.validate()}});if(a.hasRules("=#")&&(c=_v_().rules(a.config.rules).parsedRules["=#"],c=m.getElementById(c)))a.on("input keyup",function(){a.validate({highlight:!!a.value})},c);if(!~b.indexOf("blur")&&"change"!==b)a.on("blur",function(){a.get("rules")&&(a.timer&&clearTimeout(a.timer),(!a.valid||
!a.hasRules("request"))&&a.validate({no_timeout:!0}))});a.validate({silence:!0});a.inited=!0;return a};j.setRules=function(a,b){this.set({rules:a},b);this.validate(b);return this};j.hasRules=function(a){return _v_().rules(this.get("rules")).hasRule(a)};j.addRules=function(a,b){return this.setRules(_v_().rules(this.get("rules")).addRule(a).rule,b)};j.delRule=function(a,b){return this.setRules(_v_().rules(this.get("rules")).delRule(a).rule,b)};j.error=function(a){this.valid=!a?!0:!1;if(!this.highlight&&
!this.valid)return this;a=this.get("errorClass");this.valid?(this.removeClass(a),this.data("error",null)):(this.addClass(a),this.data("error","1"));return this};j.hold=function(a){var b=this.data("holded");this.holded=a===p?!this.holded:!0===a?!0:!1;this.data("holded",this.holded?1:null);!b&&!0===this.holded?this.parent.holded++:b&&!1===this.holded&&this.parent.holded--;this.parent.submitControl();return this};j.validate=function(a){var b=this.el,c=this.attr("type"),d=!0,e=this.get("own"),g=this.get("request"),
f=this.get("rules"),h=_v_(this.el.value||"").rules(f),c="checkbox"==c,j=h.hasRule("*");if(!f)return d;a=a||{};this.silence=!0===a.silence?!0:!1;this.highlight=!1===a.highlight||!0===a.silence?!1:!0;this.fire_event=!1===a.fire_event||!0===a.silence?!1:!0;this.silence||(this.execute("before"),this.trigger(this.get("eventBefore")),this.trigger(this.validationStart));if("function"==typeof e)d=e.call(this.el);else if(c)!b.checked&&j&&(d=!1);else{if(j||0<this.el.value.length)d=h.validate();if(g&&d)return this.requestValidate(a),
this.highlight=!0,null}d?this.__validationSuccess():this.__validationError();this.fire_event=this.highlight=!0;this.silence=!1;return d};j.__validationStart=function(){};j.__validationError=function(){this.trigger(this.get("eventError"));this.parent.invalid+=this.valid?1:0;this.parent.submitControl();this.error(!0);this.execute("onerror")};j.__validationSuccess=function(){this.trigger(this.get("eventValid"));this.parent.invalid-=!this.valid?1:0;this.parent.submitControl();this.error(!1);this.execute("onvalid")};
j.requestValidate=function(a){var b=this,c=b.attr("name"),d=b.el.value,e=b.get("request"),g=b.parent.button(!b.el?null:b.el.getAttribute("name")),f="post"==e.method.toLowerCase()?"POST":"GET",h=e.data||{},j,k=e.url||x.location.href;"GET"==f?(k+=~k.indexOf("?")?"&":"?",k+=c+"="+d):h[c]=d;j=k;var c=a.no_timeout?0:e.timeout||0,l=function(){var a=b.xhr;1==a.readyState&&b.execute(e.start,[a]);if(4==a.readyState&&200==a.status){var c=!0===b.execute(e.end,[a.response])?!0:!1;b["__validation"+(c?"Success":
"Error")]()}if(4==a.readyState||0==a.readystate)b.processing(!1).hold(!1),g&&g.processing(!1)},m=function(){b.processing(!0).hold(!0);g&&g.processing(!0);var a=n.newRequest();b.xhr=a;a.onreadystatechange=l;a.open(f,j,!0);a.setRequestHeader("Accept-Language","en");"POST"==f?(a.setRequestHeader("Content-type","application/x-www-form-urlencoded; charset=UTF-8"),a.send(E(h))):a.send(null)};if(b.xhr&&(0!==b.xhr.readyState||4!==b.xhr.readyState))b.xhr.abort(),b.processing(!1).hold(!1),g&&g.processing(!1);
b.xhrTimeout&&clearTimeout(b.xhrTimeout);b.hold(!1);0<c&&!0!==a.no_timeout?b.xhrTimeout=setTimeout(function(){m()},c):m()};j.execute=function(a,b){if(!this.silence)return"string"==typeof a&&(a=this.get(a)),this.parent.execute(this.el,a,b)};var t=function(a,b){var c=this.attr("type");this.parent=a;this.el=b;this.config={};this.events=[];this.name=c="submit"===c?c:this.data("check");this.set(w(k(a.config),k(a.config.buttons?a.config.buttons[c]:{})));return this.init()};h(t,f);f=t.prototype;f.init=function(){var a=
this,b=a.el,c=a.parent;a.inited&&a.destroy();if("submit"==b.type||b==c.get("submitButton"))a.on("click",function(a){a.preventDefault();c.form.onsubmit(a);return!1});else a.on("click",function(){var b=c.field(a.data("check"));b&&b.validate({no_timeout:!0})});this.inited=!0;return this};f.disable=function(){this.addClass(this.get("disabledClass"));return this};f.enable=function(){this.removeClass(this.get("disabledClass"));return this};var w=function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);
return a},k=function(a){return"[object Array]"==Object.prototype.toString.call(a)?a.slice():w({},a)},l=function(a,b){for(var c=-1,d=a?a.length:0;++c<d;)if(a[c]===b)return c;return-1},u=function(a,b,c){switch(c){case null:a&&a.removeAttribute("data-"+b);break;case p:return!a?null:a.getAttribute("data-"+b);default:s(a,"data-"+b,c)}},s=function(a,b,c){if(!a)return null;a.setAttribute(b,c)},n={_factories:[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}],
_factory:null,newRequest:function(){if(null!==n._factory)return n._factory();for(var a=0;a<n._factories.length;a++)try{var b=n._factories[a],c=b();if(null!==c)return n._factory=b,c}catch(d){}n._factory=function(){throw Error("Object XMLHttpRequest not supported");};n._factory()}},E=function(a){var b=[],c=/%20/g,d;for(d in a){var e=encodeURIComponent(d).replace(c,"+")+"=",e=e+encodeURIComponent(a[d].toString()).replace(c,"+");b.push(e)}return b.join("&")}})(window,document);
