/* tFormer v0.5.1*/
(function(x,p,q){var z=["button","submit"],A="text password select-one checkbox textarea range number email hidden file date datetime-local search tel time url month week".split(" "),B=["checkbox","select-one","select","file"],C="number date datetime-local time month week range".split(" "),D="timeout requestTimeout request validClass errorClass disabledClass processingClass rules validateEvent before onerror onvalid own eventBefore eventError eventValid".split(" "),r={errorClass:"error",processingClass:"processing",
disabledClass:"disabled",validClass:"valid",eventBefore:"tFormer:before",eventError:"tFormer:error",eventValid:"tFormer:valid",timeout:0,requestTimeout:2E3,validateEvent:"input keyup",fields:{},buttons:{},submitButtonControl:!0,submitButton:null},s=function(a,c){if(!(this instanceof s))return new s(a,c);var b=a,b="string"===typeof b?p.forms[b]:b,b=this.form="[object HTMLFormElement]"==toString.call(b)?b:null;if(null===this.form)return null;if(!b?0:b.getAttribute("empowered")){a:{for(var d=0,f=this.cache.length;d<
f;d++)if(this.cache[d].form==b){b=this.cache[d];break a}b=null}if(b)return b.set(c),b}else t(b,"empowered",1),t(b,"novalidate","novalidate");this.config=this.config||l(r);this.set(c);this.init();this.cache.push(this);return this},e=s.prototype;e.cache=[];e.init=function(){if(this.inited)return this;this.fields={};this.buttons={};this.inited=!0;this.invalid=this.holded=this.locked=0;this.valid=!0;this.fields={};this.buttons={};this.xhr={};this.xhrTimeout={};var a=this.get("submitButton");a&&(this.buttons.submit=
new u(this,a));for(var a=0,c=this.form.length;a<c;a++){var b=this.form[a],d=b.type,f="button"!==d?!b?null:b.getAttribute("name"):v(b,"check");-1!==k(A,d)&&f&&(this.fields[f]=new y(this,b));-1!==k(z,d)&&(f="submit"==d?d:f)&&!("submit"==f&&this.button[f])&&(this.buttons[f]=new u(this,b))}var j=this;this.form.onsubmit=function(a){a=a||x.event;var b=j.button("submit"),c=j.get("submitButtonControl"),d="function"==typeof j.get("submit"),f=b.get("processingClass"),e=j.valid&&d,g=function(a){a.preventDefault?
a.preventDefault():a.returnValue=!1};if(f&&b.hasClass(f)||j.locked)return g(a),!1;e&&g(a);j.valid&&(c&&b.processing(!0),d&&j.execute(j.form,"submit",[a,j]));if(e)return!1;try{if(!j.valid&&!j.validate())return g(a),b.processing(!1),!1;if(d)return g(a),j.execute(j.form,"submit",[a,j]),!1;j.form.submit();return!0}catch(h){}};this.validate({highlight:!1,fire_event:!1,silence:!0});return this.submitControl()};e.destroy=function(){for(var a in this.fields)this.fields[a].destroy();for(a in this.buttons)this.buttons[a].destroy();
this.inited=!1;return this};e.drop=function(){var a=this.fields,c=this.buttons;this.destroy();this.set(l(r));for(var b in a)a[b].drop();for(b in c)c[b].drop();this.locked=0;return this.init()};e.validate=function(a){var c=this.fields,b=0,d;for(d in c)b+=c[d].validate(a||{})?0:1;this.invalid=b;this.valid=0===b;return 0===b};e.toObject=function(){var a=this.fields,c={},b;for(b in a){var d=a[b].el;"checkbox"==d.type?c[b]=d.checked:"radio"==d.type?(c[b]||(c[b]=""),d.checked&&(c[b]=d.value)):c[b]=d.value}return c};
e.get=function(a){return this.config[a]};e.set=function(a){var c=this.inited;c&&this.destroy();this.config=w(this.config,a);c&&this.init();return this};e.field=function(a){return this.fields[a]};e.button=function(a){return this.buttons[a]};e.submit=function(a){if(!this.config)return this;"function"==typeof a&&(this.config.submit=a);return this};e.submitControl=function(a){var c=this.button("submit"),b=this.get("submitButtonControl");this.valid=0===this.invalid&&0===this.holded&&0===this.locked;a=
!1===a||!0===a?a:this.valid;if(c&&b)c[a?"enable":"disable"]();return this};e.submitDisable=function(){return this.submitControl(!1)};e.submitEnable=function(){return this.submitControl(!0)};e.processing=function(a){var c=this.button("submit");c&&c.processing(a);return this};e.lock=function(a){this.locked+=a||1;return this.submitControl(!1)};e.unlock=function(a){this.locked-=a||1;return this.submitControl()};e.execute=function(a,c,b){"string"==typeof c&&(c=this.get(c));return"function"==typeof c?c.apply(a,
b||[]):null};x.tFormer=s;var e=function(){},g=e.prototype;g.destroy=function(){for(var a=this.el,c=this.events,b=0,d=c.length;b<d;b++)this.off(c[0][0],c[0][1]);this.removeClass(this.get("errorClass"));this.removeClass(this.get("desabledClass"));this.removeClass(this.get("processignClass"));v(a,"holded",null);v(a,"error",null);this.timer&&clearTimeout(this.timer);this.xhr&&this.xhr.abort();this.xhrTimeout&&clearTimeout(this.xhrTimeout);this.valid||(this.parent.invalid=0!==this.parent.invalid?this.parent.invalid-
1:0);this.parent.submitControl();this.inited=!1;return this};g.drop=function(){return this.set(l(r))};g.set=function(a){var c=!this.el?null:this.el.getAttribute("name"),b=this.inited;b&&this.destroy();for(var d in a)if(~k(D,d)){var f=d,e=a[d];this.config[f]=e;this.parent.config.fields[c]||(this.parent.config.fields[c]=l(r));this.parent.config.fields[c][f]=e}b&&this.init();return this};g.get=function(a){return this.config[a]};g.on=function(a,c,b){b=b||this.el;a=a.split(" ");for(var d=0,f=a.length;d<
f;d++)b.addEventListener?b.addEventListener(a[d],c,!1):element.attachEvent?b.attachEvent("on"+a[d],c):b[a[d]]=c,this.events.push([a[d],c]);return this};g.off=function(a,c){var b=this.el,d=this.events;a=a.split(" ");if(!c){for(var b=0,f=d.length;b<f;b++)-1!==k(a,d[b][0])&&d.splice(b,1);return this}b.removeEventListener?b.removeEventListener(a,c,!1):b.detachEvent?b.detachEvent("on"+a,c):b[a]=null;b=0;for(f=d.length;b<f;b++)if(-1!==k(a,d[b][0])&&d[b][1]==c){d.splice(b,1);break}return this};g.trigger=
function(a){var c=this.el,b;if(!this.silence){if(p.createEventObject)return b=p.createEventObject(),c.fireEvent("on"+a,b);b=p.createEvent("HTMLEvents");b.initEvent(a,!0,!0);return!c.dispatchEvent(b)}};g.addClass=function(a){var c=this.el,b=c.className.split(" ")||[];if(-1===k(b,a)){b.push(a);a=b;if("[object Array]"==Object.prototype.toString.call(a))for(var b=[],d=0,f=a.length;d<f;d++)""!==a[d]&&b.push(a[d]);else b=void 0;c.className=0<b.length?b.join(" "):""}return this};g.removeClass=function(a){var c=
this.el;this.hasClass(a)&&(c.className=c.className.replace(RegExp("(\\s|^)"+a+"(\\s|$)")," "));return this};g.hasClass=function(a){return!!~(" "+this.el.className+" ").indexOf(" "+a+" ")};g.data=function(a,c){var b=v(this.el,a,c);return c===q?b:this};g.attr=function(a,c){var b=this.el;switch(c){case null:b&&b.removeAttribute(a);break;case q:return!b?null:b.getAttribute(a);default:t(b,a,c)}};g.processing=function(a){var c=this.get("processingClass"),b=this.hasClass(c);!1===a||null===a&&b?this.removeClass(c):
(!0===a||null===a&&b)&&this.addClass(c);return this};var g=function(a,c){var b=function(){};b.prototype=c.prototype;a.prototype=new b;a.prototype.constructor=a;a.superclass=c.prototype},y=function(a,c){var b=c.type,d,f,e,g,h=[];this.parent=a;this.el=c;this.config={};this.events=[];d=this.attr("name");f=null!==this.attr("required");e=this.attr("min");g=this.attr("max");d=a.config.fields?a.config.fields[d]:{};"string"==typeof d&&(d={rules:d});this.set(w(l(a.config),l(d)));this.config.rules=this.config.rules||
this.data("rules");f&&h.push("*");"email"==b&&h.push("@");"url"==b&&h.push("url");"number"==b&&(h.push("num"),null!==e&&h.push(">"+e),null!==g&&h.push("<"+g));0<h.length&&(this.config.rules=_v_("").rules(this.config.rules||this.data("rules")).addRule(h.join(" ")).rule);this.value=c.value;this.validationStart="v_start";this.validationSuccess="v_success";this.validationError="v_error";this.fire_event=this.highlight=!0;this.silence=!1;return this.init()};g(y,e);var h=y.prototype;h.init=function(){var a=
this,c=a.el.value,b=a.attr("type"),d="checkbox"==b;if(a.inited)return a;a.events=[];a.valid=!0;a.holded=!1;a.value=c;c=a.get("validateEvent");~k(C,b)&&-1===c.indexOf("change")&&(c=c.split(" "),c.push("change"),c=c.join(" "));~k(B,b)&&(c="change");a.set({validateEvent:c});a.on(c,function(){if(a.get("rules")&&(a.value!=a.el.value||d)){a.value=a.el.value;a.removeClass(a.get("errorClass"));a.removeClass(a.get("processingClass"));a.parent.invalid+=a.valid?1:0;a.valid=!1;a.removeClass(a.get("errorClass"));
a.parent.submitControl();var b=a.get("timeout");0<a.get("timeout")?(a.timer&&clearTimeout(a.timer),a.timer=setTimeout(function(){a.validate()},b)):a.validate()}});if(a.hasRules("=#")&&(b=_v_().rules(a.config.rules).parsedRules["=#"],b=p.getElementById(b)))a.on("input keyup",function(){a.validate({highlight:!!a.value})},b);if(!~c.indexOf("blur")&&"change"!==c)a.on("blur",function(){a.get("rules")&&(a.timer&&clearTimeout(a.timer),a.validate({no_timeout:!0}))});a.validate({silence:!0});a.inited=!0;return a};
h.setRules=function(a,c){this.set({rules:a},c);this.validate(c);return this};h.hasRules=function(a){return _v_().rules(this.get("rules")).hasRule(a)};h.addRules=function(a,c){return this.setRules(_v_().rules(this.get("rules")).addRule(a).rule,c)};h.delRule=function(a,c){return this.setRules(_v_().rules(this.get("rules")).delRule(a).rule,c)};h.error=function(a){this.valid=!a?!0:!1;if(!this.highlight&&!this.valid)return this;a=this.get("errorClass");this.valid?(this.removeClass(a),this.data("error",
null)):(this.addClass(a),this.data("error","1"));return this};h.hold=function(a){var c=this.data("holded");this.holded=a===q?!this.holded:!0===a?!0:!1;this.data("holded",this.holded?1:null);!c&&!0===this.holded?this.parent.holded++:c&&!1===this.holded&&this.parent.holded--;this.parent.submitControl();return this};h.validate=function(a){var c=this.el,b=this.attr("type"),d=!0,f=this.get("own"),e=this.get("request"),g=this.get("rules"),h=_v_(this.el.value||"").rules(g),b="checkbox"==b,m=h.hasRule("*");
if(!g)return d;a=a||{};this.silence=!0===a.silence?!0:!1;this.highlight=!1===a.highlight||!0===a.silence?!1:!0;this.fire_event=!1===a.fire_event||!0===a.silence?!1:!0;this.silence||(this.execute("before"),this.trigger(this.get("eventBefore")),this.trigger(this.validationStart));if("function"==typeof f)d=f.call(this.el);else if(b)!c.checked&&m&&(d=!1);else{if(m||0<this.el.value.length)d=h.validate();if(e&&d)return this.requestValidate(a),this.highlight=!0,null}d?this.__validationSuccess():this.__validationError();
this.fire_event=this.highlight=!0;this.silence=!1;return d};h.__validationStart=function(){};h.__validationError=function(){this.trigger(this.get("eventError"));this.parent.invalid+=this.valid?1:0;this.parent.submitControl();this.error(!0);this.execute("onerror")};h.__validationSuccess=function(){this.trigger(this.get("eventValid"));this.parent.invalid-=!this.valid?1:0;this.parent.submitControl();this.error(!1);this.execute("onvalid")};h.requestValidate=function(a){var c=this,b=c.attr("name"),d=c.value,
f=c.get("request"),e="post"==f.method.toLowerCase()?"POST":"GET",g=f.data||{},h,m=f.url||x.location.href;"GET"==e?(m+=~m.indexOf("?")?"&":"?",m+=b+"="+d):g[b]=d;h=m;var b=a.no_timeout?0:f.timeout||0,l=function(){var a=c.xhr;1==a.readyState&&c.execute(f.start,[a]);4==a.readyState&&200==a.status&&(a=!0===c.execute(f.end,[a.response])?!0:!1,c.processing(!1).hold(!1),c["__validation"+(a?"Success":"Error")]())},k=function(){var a=n.newRequest();c.xhr=a;a.onreadystatechange=l;c.processing(!0).hold(!0);
a.open(e,h,!0);a.setRequestHeader("Accept-Language","en");"POST"==e?(a.setRequestHeader("Content-type","application/x-www-form-urlencoded; charset=UTF-8"),a.send(E(g))):a.send(null)};c.xhr&&c.xhr.abort();c.xhrTimeout&&clearTimeout(c.xhrTimeout);c.hold(!1);0<b&&!0!==a.no_timeout?c.xhrTimeout=setTimeout(function(){k()},b):k()};h.execute=function(a,c){if(!this.silence)return"string"==typeof a&&(a=this.get(a)),this.parent.execute(this.el,a,c)};var u=function(a,c){var b=this.attr("type");this.parent=a;
this.el=c;this.config={};this.events=[];this.name=b="submit"===b?b:this.data("check");this.set(w(l(a.config),l(a.config.buttons?a.config.buttons[b]:{})));return this.init()};g(u,e);e=u.prototype;e.init=function(){var a=this,c=a.el,b=a.parent;a.inited&&a.destroy();if("submit"==c.type||c==b.get("submitButton"))a.on("click",function(a){a.preventDefault();b.form.onsubmit(a);return!1});else a.on("click",function(){var c=b.field(a.data("check"));c&&c.validate({no_timeout:!0})});this.inited=!0;return this};
e.disable=function(){this.addClass(this.get("disabledClass"));return this};e.enable=function(){this.removeClass(this.get("disabledClass"));return this};var w=function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b]);return a},l=function(a){return"[object Array]"==Object.prototype.toString.call(a)?a.slice():w({},a)},k=function(a,c){for(var b=-1,d=a?a.length:0;++b<d;)if(a[b]===c)return b;return-1},v=function(a,c,b){switch(b){case null:a&&a.removeAttribute("data-"+c);break;case q:return!a?null:a.getAttribute("data-"+
c);default:t(a,"data-"+c,b)}},t=function(a,c,b){if(!a)return null;a.setAttribute(c,b)},n={_factories:[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}],_factory:null,newRequest:function(){if(null!==n._factory)return n._factory();for(var a=0;a<n._factories.length;a++)try{var c=n._factories[a],b=c();if(null!==b)return n._factory=c,b}catch(d){}n._factory=function(){throw Error("Object XMLHttpRequest not supported");
};n._factory()}},E=function(a){var c=[],b=/%20/g,d;for(d in a){var e=encodeURIComponent(d).replace(b,"+")+"=",e=e+encodeURIComponent(a[d].toString()).replace(b,"+");c.push(e)}return c.join("&")}})(window,document);
